Tracker:AddLocations("locations/Overview.json")
Tracker:AddLocations("locations/Start Menu.json")
Tracker:AddLocations("locations/Homelanda.json")
Tracker:AddLocations("locations/Oaklaville.json")
Tracker:AddLocations("locations/Stanhamn.json")
Tracker:AddLocations("locations/Logcity.json")
Tracker:AddLocations("locations/Kiiruberg.json")
Tracker:AddLocations("locations/Mountain Top.json")
Tracker:AddLocations("locations/Basto.json")